- name: Create code directory
  file:
    path: "{{ code_dir }}"
    state: directory

# make sure to clear the packaging dirctory to have a clean slate
- file:
    path: "{{ spec_dir }}"
    state: "{{ item }}"
  loop:
    - absent
    - directory

- name: copy packaging information
  synchronize:
    src: ../packaging/
    dest: "{{ spec_dir }}"

- file:
    path: "{{ srpm_dir }}"
    state: directory

- file:
    path: "{{ rpms_dir }}"
    state: directory

- file:
    path: "{{ mock_dir }}"
    state: directory

- name: copy mock config files
  copy:
    src: "{{ item }}"
    dest: "{{ mock_dir }}"
  loop:
    - /etc/mock/centos-stream+epel-next-8-{{ os_arch }}.cfg
    - /etc/mock/centos-stream+epel-next-9-{{ os_arch }}.cfg
    - /etc/mock/rhel-8-{{ os_arch }}.cfg
    - /etc/mock/rhel-9-{{ os_arch }}.cfg
    - glusterfs-nightly-repo.tpl
    - ceph-repo.tpl.j2
    - epel-restricted.tpl

- name: copy fedora mock config files
  copy:
    src: "{{ item }}"
    dest: "{{ mock_dir }}"
  with_fileglob:
    - "/etc/mock/fedora-*-{{ os_arch }}.cfg"

- include_tasks: repo.yml
  tags: repos
