- name: build centos {{ os_vers }} rpms
  command: /usr/bin/mock --root {{ mock_config }} --resultdir {{ rpms_dir }}/{{ samba_major_version }}/centos/{{ os_vers }}/{{ os_arch }} --define "vendor_dist {{ vendor_dist }}" --rebuild {{ srpm_dir }}/{{ samba_srpm }}
