- name: build centos {{ os_vers }} rpms
  command: /usr/bin/mock --root {{ mock_dir }}/centos-stream+epel-next-{{ os_vers }}-{{ os_arch }}.cfg --resultdir {{ rpms_dir }}/{{ samba_major_version }}/centos/{{ os_vers }}/{{ os_arch }} --define "vendor_dist {{ vendor_dist }}" --rebuild {{ srpm_dir }}/{{ samba_srpm }}
