- hosts: localhost
  connection: local
  become: no
  vars:
    refspec: "{{ refspec }}"
    os_vers: "{{ version | default('40') }}"
  vars_files:
    - vars.yml
  roles:
    - prep.dirs
    - set.version
    - make.tarball
    - make.srpm
    - build.rpms.fedora
