- hosts: localhost
  connection: local
  become: no
  vars:
    refspec: "{{ refspec }}"
    os_vers: "{{ version | default('9') }}"
    os_arch: "{{ arch | default('x86_64') }}"
    vendor_dist: "{{ vendor_dist_suffix | default('%{nil}') }}"
  vars_files:
    - vars.yml
  roles:
    - prep.dirs
    - set.version
    - make.tarball
    - make.srpm
    - build.rpms.centos
