- hosts: localhost
  connection: local
  become: no
  vars:
    os_vers: "{{ version | default('9') }}"
    os_arch: "{{ arch | default('x86_64') }}"
  vars_files:
    - vars.yml
  roles:
    - prep.dirs
