---
- hosts: localhost
  connection: local
  become: no
  vars:
    refspec: "{{ refspec }}"
    os_vers: "{{ version }}"
  vars_files:
    - vars.yml
  roles:
    - set.version
    - test.rpms.fedora
