- hosts: localhost
  connection: local
  become: no
  vars:
    refspec: "{{ refspec }}"
    os_vers: "{{ version | default('9') }}"
  vars_files:
    - vars.yml
  roles:
    - prep.dirs
    - set.version
    - test.rpms.centos
